package com.ws101.ada.fajardo.EcommerceApi.entity;

import jakarta.persistence.*;

/**
 * Product entity representing items in the e-commerce catalog.
 * Maps to the 'products' table in the MySQL database.
 * 
 * This entity stores all product information including pricing,
 * inventory, and descriptive details for the frontend display.
 * 
 * @author Acepogi111
 * @version 1.0
 * @since 2025-05-09
 */
@Entity
@Table(name = "products")
public class Product {

    /**
     * Primary key identifier for the product.
     * Auto-generated by the database using IDENTITY strategy.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Name of the product as displayed to customers.
     * Cannot be null.
     */
    @Column(nullable = false)
    private String name;

    /**
     * Detailed description of the product features and specifications.
     */
    @Column(columnDefinition = "TEXT")
    private String description;

    /**
     * Current selling price of the product in PHP.
     * Stored as double for decimal precision.
     */
    @Column(nullable = false)
    private Double price;

    /**
     * Available stock quantity in inventory.
     * Used to prevent overselling products.
     */
    @Column(nullable = false)
    private Integer stock;

    /**
     * URL or path to the product image.
     * Used by frontend for product display.
     */
    private String imageUrl;

    // Default constructor required by JPA
    public Product() {}

    /**
     * Constructs a new Product with all required fields.
     * 
     * @param name        the product name
     * @param description the product description
     * @param price       the selling price
     * @param stock       the available quantity
     * @param imageUrl    the product image URL
     */
    public Product(String name, String description, Double price, Integer stock, String imageUrl) {
        this.name = name;
        this.description = description;
        this.price = price;
        this.stock = stock;
        this.imageUrl = imageUrl;
    }

    // Getters and Setters with Javadoc
    
    /**
     * Gets the product ID.
     * @return the unique product identifier
     */
    public Long getId() { return id; }

    /**
     * Sets the product ID.
     * @param id the unique identifier to set
     */
    public void setId(Long id) { this.id = id; }

    /**
     * Gets the product name.
     * @return the name of the product
     */
    public String getName() { return name; }

    /**
     * Sets the product name.
     * @param name the name to set
     */
    public void setName(String name) { this.name = name; }

    /**
     * Gets the product description.
     * @return the detailed description
     */
    public String getDescription() { return description; }

    /**
     * Sets the product description.
     * @param description the description to set
     */
    public void setDescription(String description) { this.description = description; }

    /**
     * Gets the product price.
     * @return the price in PHP
     */
    public Double getPrice() { return price; }

    /**
     * Sets the product price.
     * @param price the price to set
     */
    public void setPrice(Double price) { this.price = price; }

    /**
     * Gets the available stock quantity.
     * @return the stock count
     */
    public Integer getStock() { return stock; }

    /**
     * Sets the available stock quantity.
     * @param stock the stock count to set
     */
    public void setStock(Integer stock) { this.stock = stock; }

    /**
     * Gets the product image URL.
     * @return the image URL path
     */
    public String getImageUrl() { return imageUrl; }

    /**
     * Sets the product image URL.
     * @param imageUrl the image URL to set
     */
    public void setImageUrl(String imageUrl) { this.imageUrl = imageUrl; }
}